/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#604100',
        'on-tertiary-fixed-variant': '#3c4854',
        'secondary-fixed': '#ffdeac',
        'primary-fixed': '#7df4ff',
        'tertiary-container': '#cedbea',
        'on-tertiary': '#25323d',
        'on-error-container': '#ffdad6',
        'error-container': '#93000a',
        'tertiary-fixed-dim': '#bbc8d6',
        'outline-variant': '#3b494b',
        'on-tertiary-container': '#53606c',
        'primary-fixed-dim': '#00dbe9',
        'on-primary': '#00363a',
        'secondary-container': '#feb300',
        'on-surface': '#e3e2e3',
        background: '#121315',
        'inverse-on-surface': '#303032',
        'surface-container-low': '#1b1c1d',
        'on-primary-fixed': '#002022',
        outline: '#849495',
        'secondary-fixed-dim': '#ffba38',
        'tertiary-fixed': '#d7e4f3',
        'surface-dim': '#121315',
        'primary-container': '#00f0ff',
        'on-primary-fixed-variant': '#004f54',
        'inverse-primary': '#006970',
        tertiary: '#f0f6ff',
        error: '#ffb4ab',
        primary: '#dbfcff',
        'on-secondary-fixed': '#281900',
        'inverse-surface': '#e3e2e3',
        'surface-container-high': '#292a2b',
        'on-secondary': '#432c00',
        'surface-bright': '#38393a',
        surface: '#121315',
        'on-tertiary-fixed': '#101d27',
        'on-background': '#e3e2e3',
        secondary: '#ffd799',
        'surface-container-lowest': '#0d0e0f',
        'on-surface-variant': '#b9cacb',
        'surface-container-highest': '#343536',
        'surface-variant': '#343536',
        'surface-container': '#1f2021',
        'on-error': '#690005',
        'surface-tint': '#00dbe9',
        'on-secondary-container': '#6a4800',
        'on-primary-container': '#006970',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-sm': '0.5rem',
        'margin-mobile': '1rem',
        gutter: '1.5rem',
        'space-xs': '0.25rem',
        'gutter-mobile': '0.75rem',
        'space-xl': '4rem',
        margin: '3rem',
        'space-lg': '2rem',
        'space-md': '1rem',
      },
      fontFamily: {
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-xl': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'label-md': ['"JetBrains Mono"', 'monospace'],
        'body-md': ['Geist', 'sans-serif'],
        'label-xs': ['"JetBrains Mono"', 'monospace'],
        'label-lg': ['"JetBrains Mono"', 'monospace'],
        'headline-md': ['Geist', 'sans-serif'],
        'headline-xl-mobile': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['40px', { lineHeight: '44px', letterSpacing: '-0.03em', fontWeight: '500' }],
        'headline-xl': ['56px', { lineHeight: '60px', letterSpacing: '-0.04em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '26px', letterSpacing: '-0.01em', fontWeight: '400' }],
        'label-md': ['11px', { lineHeight: '16px', letterSpacing: '0.06em', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '22px', letterSpacing: '-0.005em', fontWeight: '400' }],
        'label-xs': ['9px', { lineHeight: '12px', letterSpacing: '0.1em', fontWeight: '400' }],
        'label-lg': ['13px', { lineHeight: '18px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '28px', letterSpacing: '-0.02em', fontWeight: '500' }],
        'headline-xl-mobile': ['36px', { lineHeight: '40px', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '500' }],
      },
      keyframes: {
        blink: {
          '0%, 45%': { opacity: '1' },
          '50%, 95%': { opacity: '0.2' },
          '100%': { opacity: '1' },
        },
        scan: {
          '0%': { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
      },
      animation: {
        blink: 'blink 1s steps(1) infinite',
        scan: 'scan 6s linear infinite',
      },
    },
  },
  plugins: [],
};